---
title: "Example: Running the whole workflow"
author: "Jakob Skelmose, Rasmus Rask, Lars Nielsen, Charles Vesteghem, Jennifer Bartell, Martin Bøgsted"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example Running the whole workflow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(simulacrumWorkflowR)
library(survival)
library(openxlsx)
library(broom)
library(openxlsx)
```


```{r}
dir <- "C:/Users/p90j/Documents/simulacrum_v2.1.0/Data"
data_frames_lists <- read_simulacrum(dir, selected_files = c("sim_av_patient", "sim_av_tumour")) 
```


#dfs
```{r}
SIM_AV_PATIENT <- data_frames_lists$sim_av_patient
SIM_AV_TUMOUR <- data_frames_lists$sim_av_tumour
```

# demonstration of the sql query translator 
```{r}
query2 <- "select *
from SIM_AV_PATIENT
limit 500;"
```

```{r}
print(sqlite2oracle(query2))
```

# Run query on SQLite database
#### Select the variables of interest
```{r}
df1 <- query_sql("SELECT 
SIM_AV_PATIENT.PATIENTID, SIM_AV_PATIENT.GENDER, SIM_AV_PATIENT.VITALSTATUS, SIM_AV_PATIENT.VITALSTATUSDATE, SIM_AV_TUMOUR.DIAGNOSISDATEBEST, SIM_AV_TUMOUR.AGE, SIM_AV_TUMOUR.PERFORMANCESTATUS, SIM_AV_TUMOUR.SITE_ICD10_O2_3CHAR

FROM SIM_AV_PATIENT
INNER JOIN SIM_AV_TUMOUR 
    ON SIM_AV_PATIENT.patientid = SIM_AV_TUMOUR.patientid;
")
```

# Additional preprocessing
```{r}
df_surv <- survival_days(df1)
df_surv$VITALSTATUS <- ifelse(df_surv$VITALSTATUS == "A", 1,
                              ifelse(df_surv$VITALSTATUS == "D", 0, NA))

df_complete <- cancer_grouping(df_surv)
extended_summary(df_complete)
```


# example of a Cox model of the synthetic data
```{r}
cox_model <- coxph(Surv(diff_date, VITALSTATUS) ~ AGE + factor(GENDER) + factor(PERFORMANCESTATUS), data=df_complete)
summary(cox_model)
```

# Example of a Logistic regression of the synthetic data
```{r}
log_model <- glm(VITALSTATUS ~ AGE + factor(GENDER) + factor(PERFORMANCESTATUS), data=df_complete, family = "binomial")
summary(log_model)
```

# Save models as HTML files 
```{r}
output_dir <- "./Outputs"
create_dir(output_dir)

cox_model_sum <- tidy(cox_model)
write.xlsx(cox_model_sum, file.path(output_dir, "cox_model.xlsx"))

log_model_sum <- tidy(log_model)
write.xlsx(log_model_sum, file.path(output_dir, "log_model.xlsx"))
```

```{r}
create_workflow(
  libraries = '              
library(survival)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
',
  query = "                  
SELECT *
FROM sim_av_patient
INNER JOIN sim_av_tumour ON sim_av_patient.patientid = sim_av_tumour.patientid;",
  data_management = '        
df2 <- survival_days(df1)

df21 <- df2

df21$VITALSTATUS <- ifelse(df21$VITALSTATUS == "A", 1,
                              ifelse(df21$VITALSTATUS == "D", 0, NA))
',
  analysis = '
cox_model <- coxph(Surv(diff_date, VITALSTATUS) ~ AGE + factor(GENDER.x) + factor(PERFORMANCESTATUS), data=df21)
log_model <- glm(VITALSTATUS ~ AGE + factor(GENDER.x) + factor(PERFORMANCESTATUS), data=df21, family = "binomial")
',
  model_results = '
cox_model_sum <- tidy(cox_model)
write.xlsx(cox_model_sum, "cox_model.xlsx")

log_model_sum <- tidy(log_model) 
write.xlsx(log_model_sum, "log_model.xlsx")

')

```


```{r}
stop <- stop_time()
compute_time_limit(start, stop)
```